version: "3.6"

services:
  aspnetcorespa:
    image: ${DOCKER_REGISTRY-}poc-aspnetcore3
    build:
      context: .
      dockerfile: web.dockerfile
    networks:
      - app-network

  aspnetcorests:
    image: ${DOCKER_REGISTRY-}poc-sts
    build:
      context: .
      dockerfile: sts.dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
